version: '3.9'
services:
  mongoDB:
    image: mongo
    volumes:
      - mongoDATA:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mst
      - MONGO_INITDB_ROOT_PASSWORD=clannad123

  multi-be:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     - MONGO_USERNAME=mst
    ports:
      - "80:80"
    environment:
      - MONGODB_USERNAME=mst
      - MONGODB_PASSWORD=clannad123
    volumes:
      - /app/node_modules
      - logs:/app/logs
    depends_on:
      - mongoDB
  multi-fe:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
volumes:
  mongoDATA:
    driver: local
  logs:
    driver: local